export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";

export const GET_CART_DATA_REQUEST = "GET_CART_DATA_REQUEST";
export const GET_CART_DATA_SUCCESS = "GET_CART_DATA_SUCCESS";
export const GET_CART_DATA_FAIL = "GET_CART_DATA_FAIL";

export const POST_CART_DATA_REQUEST = "POST_CART_DATA_REQUEST";
export const POST_CART_DATA_SUCCESS = "POST_CART_DATA_SUCCESS";
export const POST_CART_DATA_FAIL = "POST_CART_DATA_FAIL";
export const DELETE_CART_DATA_REQUEST = "DELETE_CART_DATA_REQUEST";
export const DELETE_CART_DATA_SUCCESS = "DELETE_CART_DATA_SUCCESS";
export const DELETE_CART_DATA_FAIL = "DELETE_CART_DATA_FAIL";
