// Wishlist Action Constants
export const WISHLIST_REQUEST = "WISHLIST_REQUEST";
export const WISHLIST_SUCCESS = "WISHLIST_SUCCESS";
export const WISHLIST_FAILURE = "WISHLIST_FAILURE";

export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_FAILURE = "ADD_TO_WISHLIST_FAILURE";

export const REMOVE_FROM_WISHLIST_REQUEST = "REMOVE_FROM_WISHLIST_REQUEST";
export const REMOVE_FROM_WISHLIST_SUCCESS = "REMOVE_FROM_WISHLIST_SUCCESS";
export const REMOVE_FROM_WISHLIST_FAILURE = "REMOVE_FROM_WISHLIST_FAILURE";

export const CLEAR_WISHLIST_REQUEST = "CLEAR_WISHLIST_REQUEST";
export const CLEAR_WISHLIST_SUCCESS = "CLEAR_WISHLIST_SUCCESS";
export const CLEAR_WISHLIST_FAILURE = "CLEAR_WISHLIST_FAILURE";

export const CHECK_WISHLIST_REQUEST = "CHECK_WISHLIST_REQUEST";
export const CHECK_WISHLIST_SUCCESS = "CHECK_WISHLIST_SUCCESS";
export const CHECK_WISHLIST_FAILURE = "CHECK_WISHLIST_FAILURE";

export const GET_WISHLIST_COUNT_REQUEST = "GET_WISHLIST_COUNT_REQUEST";
export const GET_WISHLIST_COUNT_SUCCESS = "GET_WISHLIST_COUNT_SUCCESS";
export const GET_WISHLIST_COUNT_FAILURE = "GET_WISHLIST_COUNT_FAILURE";
