// Address Management Constants
export const GET_ADDRESSES_REQUEST = "GET_ADDRESSES_REQUEST";
export const GET_ADDRESSES_SUCCESS = "GET_ADDRESSES_SUCCESS";
export const GET_ADDRESSES_FAIL = "GET_ADDRESSES_FAIL";

export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAIL = "ADD_ADDRESS_FAIL";

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL";

export const SET_DEFAULT_ADDRESS_REQUEST = "SET_DEFAULT_ADDRESS_REQUEST";
export const SET_DEFAULT_ADDRESS_SUCCESS = "SET_DEFAULT_ADDRESS_SUCCESS";
export const SET_DEFAULT_ADDRESS_FAIL = "SET_DEFAULT_ADDRESS_FAIL";

export const GET_DEFAULT_ADDRESS_REQUEST = "GET_DEFAULT_ADDRESS_REQUEST";
export const GET_DEFAULT_ADDRESS_SUCCESS = "GET_DEFAULT_ADDRESS_SUCCESS";
export const GET_DEFAULT_ADDRESS_FAIL = "GET_DEFAULT_ADDRESS_FAIL";
